### ISSUE TITLE
Expand Project Data

### ISSUE THREAD

**Issue by Cheshakoneko** [MGX-metagenomics/MGX-client#104]
**Bug**
Trying to expand Project Data 

**Exception**
`de.cebitec.mgx.client.exception.MGXServerException: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Payara Server  5.192 #badassfish - Error report</title><style type="text/css"></style> </head><body><h1>HTTP Status 500 - Internal Server Error</h1><hr/><p><b>type</b> Exception report</p><p><b>message</b>Internal Server Error</p><p><b>description</b>The server encountered an internal error that prevented it from fulfilling this request.</p><p><b>exception</b> <pre>javax.servlet.ServletException: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error</pre></p><p><b>root cause</b> <pre>javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error</pre></p><p><b>root cause</b> <pre>org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=null, type=class javax.ejb.EJBTransactionRolledbackException, genericType=class javax.ejb.EJBTransactionRolledbackException.</pre></p><p><b>note</b> <u>The full stack traces of the exception and its root causes are available in the Payara Server  5.192 #badassfish logs.</u></p><hr/><h3>Payara Server  5.192 #badassfish</h3></body></html>
	at de.cebitec.mgx.client.access.rest.AccessBase.fetchlist(AccessBase.java:101)
	at de.cebitec.mgx.client.access.rest.HabitatAccess.fetchall(HabitatAccess.java:22)
	at de.cebitec.mgx.gui.controller.HabitatAccess.fetchall(HabitatAccess.java:81)
Caused: de.cebitec.mgx.api.exception.MGXException
	at de.cebitec.mgx.gui.controller.HabitatAccess.fetchall(HabitatAccess.java:93)
[catch] at de.cebitec.mgx.gui.nodefactory.HabitatNodeFactory.addKeys(HabitatNodeFactory.java:24)
	at de.cebitec.mgx.gui.nodefactory.MGXNodeFactoryBase.createKeys(MGXNodeFactoryBase.java:48)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:190)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
`

**Comment by sjaenick** [comment]
server issue (duplicate datasource subscription), unfortunately, no way to reproduce yet. closing.
